### ISSUE TITLE
produce configure-generated files using build options and target settings rather than hard-coding

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/ffmpeg#1]
The commit https://github.com/andrewrk/ffmpeg/commit/af01e2d310f50d595d34b9111ad5cf48931e3b3a copied configure-generated source files into the repo. These are incorrectly hard-coded with the settings of the host when ./configure was evaluated. Instead, all these files should be generated by build.zig at build time.

In addition to the commit listed above:
 * libavutil/ffversion.h

**Comment by david-vanderson** [comment]
I am trying to fix this, but need guidance.

I tried (and failed) to get build.zig to create the .c files inside zig-cache and then add those to the C sources.  Is there a way to do this?  Or should build.zig create the files where they normally reside and reference the normal paths?

For the headers I was planning on replacing them with empty files in git, and putting all the #defines in build.zig.  Sound right?

**Comment by andrewrk** [comment]
For the headers, you could try something like this:

https://github.com/andrewrk/libmp3lame/blob/497568e670bfeb14ab6ef47fb6459a2251358e43/build.zig#L8-L116

More enhancements to `std.build` will be needed to additionally install such a generated header.

As for .c files, all of these things need to be done in a declarative manner with the build system. Perhaps std.build.LibExeObjStep needs to gain a new method similar to `addCSourceFile` but that accepts a `WriteFileStep` as a parameter.

**Comment by david-vanderson** [comment]
First start on the headers part here https://github.com/ziglang/zig/pull/14382

**Comment by david-vanderson** [comment]
Thanks for the guidance!  That helped me understand where to start.
