### ISSUE TITLE
build fail. no field named 'result' in struct 'zig.CrossTarget'

### ISSUE THREAD

**Issue by zhang-chuanfeng** [andrewrk/ffmpeg#12]
![image](https://github.com/andrewrk/ffmpeg/assets/59160162/1caf24dc-f3b8-4341-a741-6da7ef5338a9)
![image](https://github.com/andrewrk/ffmpeg/assets/59160162/247a7537-9195-4feb-97fe-13814366023a)

**Comment by andrewrk** [comment]
must use newer zig
