### ISSUE TITLE
The `metadata` example segfaults on certain files

### ISSUE THREAD

**Issue by y-71** [andrewrk/ffmpeg#7]
after building, i try to run the metadata script against some files and very often, 

here is an example:
https://file-examples.com/storage/fe7fa6fa10650d95e925ca2/2017/04/file_example_MP4_480_1_5MG.mp4

I run on a `Apple M2 Pro` with `macOs 13.5.1 (22G90)`

**Comment by y-71** [comment]
I've just tried the same example on a x86-64 ubuntu 20.04 machine and it worked fine

**Comment by andrewrk** [comment]
Cannot reproduce. Also the link is a 404
